import Job from "../models/Job.js";

const LOCAL_JOBS = [
  {
    title: "Frontend Developer",
    company: "Razorpay",
    team: "Payments UI",
    location: "Bangalore, India",
    workType: "Hybrid",
    experience: "1-3 Years",
    salary: "₹8-14 LPA",
    jobType: "Full Time",
    description: "Build and maintain high-performance frontend experiences for Razorpay's payment products used by millions of businesses across India.",
    skills: ["React", "TypeScript", "JavaScript", "HTML", "CSS", "Redux", "REST APIs"],
    requirements: ["Proficiency in React and TypeScript", "Strong understanding of browser rendering and performance", "Experience with design systems", "Familiarity with REST APIs"],
    companyHighlights: { rating: 4.4, size: "2,500+ employees", industry: "Fintech", culture: "High ownership, fast-paced", benefits: ["Health Insurance", "ESOPs", "Flexible Hours", "Learning Budget"] },
    source: "Local",
    externalId: "local-razorpay-fe-001",
  },
  {
    title: "Backend Engineer",
    company: "Swiggy",
    team: "Order Management",
    location: "Bangalore, India",
    workType: "Hybrid",
    experience: "2-5 Years",
    salary: "₹15-25 LPA",
    jobType: "Full Time",
    description: "Design and scale backend services that handle millions of food orders every day. You'll work on distributed systems, microservices, and high-throughput APIs.",
    skills: ["Node.js", "Go", "PostgreSQL", "Redis", "Kafka", "Docker", "Kubernetes", "REST APIs"],
    requirements: ["Strong backend experience in Node.js or Go", "Experience with distributed systems", "SQL and NoSQL databases", "Knowledge of message queues like Kafka"],
    companyHighlights: { rating: 4.2, size: "5,000+ employees", industry: "Food Tech", culture: "Move fast, break nothing", benefits: ["Health Insurance", "Free Swiggy Credits", "ESOPs", "Remote Fridays"] },
    source: "Local",
    externalId: "local-swiggy-be-001",
  },
  {
    title: "Full Stack Engineer",
    company: "CRED",
    team: "Member Experience",
    location: "Bangalore, India",
    workType: "Hybrid",
    experience: "2-4 Years",
    salary: "₹18-30 LPA",
    jobType: "Full Time",
    description: "Own end-to-end features for CRED's flagship app used by India's creditworthy population. You'll work across React Native frontend and Node.js backend.",
    skills: ["React", "React Native", "Node.js", "TypeScript", "MongoDB", "PostgreSQL", "GraphQL"],
    requirements: ["Full stack experience across React and Node.js", "Familiarity with React Native is a plus", "GraphQL API design", "Strong system design fundamentals"],
    companyHighlights: { rating: 4.5, size: "1,500+ employees", industry: "Fintech", culture: "Design-first, user-obsessed", benefits: ["Top-tier Compensation", "ESOPs", "Health & Wellness", "Learning Stipend"] },
    source: "Local",
    externalId: "local-cred-fs-001",
  },
  {
    title: "Data Engineer",
    company: "Flipkart",
    team: "Data Platform",
    location: "Bangalore, India",
    workType: "On-site",
    experience: "2-5 Years",
    salary: "₹16-28 LPA",
    jobType: "Full Time",
    description: "Build and maintain large-scale data pipelines that process petabytes of e-commerce data to power analytics, ML models, and business decisions.",
    skills: ["Python", "Apache Spark", "Hadoop", "SQL", "Airflow", "Kafka", "AWS", "Data Warehousing"],
    requirements: ["Strong Python and SQL skills", "Experience with big data tools (Spark, Hive)", "Pipeline orchestration with Airflow", "Understanding of data warehouse design"],
    companyHighlights: { rating: 4.1, size: "30,000+ employees", industry: "E-commerce", culture: "Data-driven, scale-obsessed", benefits: ["Health Insurance", "ESOPs", "Flexible Leave", "Relocation Support"] },
    source: "Local",
    externalId: "local-flipkart-de-001",
  },
  {
    title: "Machine Learning Engineer",
    company: "PhonePe",
    team: "AI/ML Platform",
    location: "Bangalore, India",
    workType: "Hybrid",
    experience: "3-6 Years",
    salary: "₹20-35 LPA",
    jobType: "Full Time",
    description: "Build and deploy ML models at scale for fraud detection, personalization, and payment success optimization on one of India's largest fintech platforms.",
    skills: ["Python", "TensorFlow", "PyTorch", "Scikit-learn", "SQL", "Spark", "MLflow", "Docker"],
    requirements: ["Strong ML fundamentals and model deployment experience", "Python expertise", "Experience with TensorFlow or PyTorch", "Knowledge of feature engineering and model monitoring"],
    companyHighlights: { rating: 4.3, size: "4,000+ employees", industry: "Fintech", culture: "Startup spirit at scale", benefits: ["Competitive Salary", "ESOPs", "Health Coverage", "L&D Budget"] },
    source: "Local",
    externalId: "local-phonepe-ml-001",
  },
  {
    title: "DevOps Engineer",
    company: "Zomato",
    team: "Platform Engineering",
    location: "Gurugram, India",
    workType: "Hybrid",
    experience: "2-5 Years",
    salary: "₹14-22 LPA",
    jobType: "Full Time",
    description: "Manage and scale cloud infrastructure supporting Zomato's food delivery and quick-commerce operations across 500+ cities.",
    skills: ["AWS", "Kubernetes", "Docker", "Terraform", "CI/CD", "GitHub Actions", "Linux", "Python"],
    requirements: ["Strong AWS and Kubernetes experience", "Infrastructure-as-code with Terraform", "CI/CD pipeline setup and maintenance", "Monitoring and incident response"],
    companyHighlights: { rating: 4.0, size: "5,000+ employees", industry: "Food Tech", culture: "Hustle culture with heart", benefits: ["Health Insurance", "Zomato Gold", "ESOPs", "Hybrid Work"] },
    source: "Local",
    externalId: "local-zomato-devops-001",
  },
  {
    title: "Software Development Engineer",
    company: "Amazon",
    team: "Amazon India",
    location: "Hyderabad, India",
    workType: "On-site",
    experience: "1-4 Years",
    salary: "₹20-40 LPA",
    jobType: "Full Time",
    description: "Build systems and services that power Amazon's marketplace, logistics, and customer experience for hundreds of millions of customers across India and globally.",
    skills: ["Java", "Python", "AWS", "Microservices", "SQL", "NoSQL", "System Design", "REST APIs"],
    requirements: ["Strong DSA and system design skills", "Proficiency in Java or Python", "Experience with AWS services", "Understanding of distributed systems"],
    companyHighlights: { rating: 4.0, size: "100,000+ employees", industry: "E-commerce / Cloud", culture: "Customer obsession, ownership", benefits: ["Top Pay", "RSUs", "Health Coverage", "Relocation"] },
    source: "Local",
    externalId: "local-amazon-sde-001",
  },
  {
    title: "React Native Developer",
    company: "Meesho",
    team: "Consumer App",
    location: "Bangalore, India",
    workType: "Hybrid",
    experience: "1-3 Years",
    salary: "₹10-18 LPA",
    jobType: "Full Time",
    description: "Build fast, reliable mobile experiences for Meesho's 150M+ users across India. You'll work on the core shopping app used by first-time internet users.",
    skills: ["React Native", "JavaScript", "TypeScript", "Redux", "REST APIs", "Android", "iOS"],
    requirements: ["Strong React Native development experience", "Published apps on Play Store / App Store", "Performance optimization for low-end devices", "Redux state management"],
    companyHighlights: { rating: 4.3, size: "3,500+ employees", industry: "Social Commerce", culture: "Inclusive, mission-driven", benefits: ["Health Insurance", "ESOPs", "Flexible Work", "Wellness Budget"] },
    source: "Local",
    externalId: "local-meesho-rn-001",
  },
  {
    title: "Cloud Solutions Architect",
    company: "Infosys",
    team: "Cloud & Infrastructure",
    location: "Pune, India",
    workType: "Hybrid",
    experience: "5+ Years",
    salary: "₹20-35 LPA",
    jobType: "Full Time",
    description: "Design and implement enterprise cloud architectures for Infosys clients across banking, insurance, and retail sectors using AWS, Azure, and GCP.",
    skills: ["AWS", "Azure", "GCP", "Terraform", "Docker", "Kubernetes", "Solution Architecture", "Python"],
    requirements: ["Cloud architect certification (AWS/Azure/GCP)", "5+ years in cloud infrastructure", "Enterprise client-facing experience", "Strong communication skills"],
    companyHighlights: { rating: 3.8, size: "300,000+ employees", industry: "IT Services", culture: "Large enterprise, global scale", benefits: ["Health Coverage", "Global Mobility", "Learning Platform", "Retirement Plan"] },
    source: "Local",
    externalId: "local-infosys-cloud-001",
  },
  {
    title: "Android Developer",
    company: "Ola",
    team: "Driver App",
    location: "Bangalore, India",
    workType: "On-site",
    experience: "2-4 Years",
    salary: "₹12-20 LPA",
    jobType: "Full Time",
    description: "Build robust Android experiences for Ola's driver and captain apps used across ride-sharing, autos, and electric vehicles in 250+ cities.",
    skills: ["Android", "Kotlin", "Java", "MVVM", "Jetpack", "REST APIs", "SQLite", "Firebase"],
    requirements: ["Strong Android development in Kotlin", "Experience with Jetpack components", "MVVM architecture", "Performance profiling and optimization"],
    companyHighlights: { rating: 3.9, size: "3,000+ employees", industry: "Mobility / EV", culture: "Mission-driven, entrepreneurial", benefits: ["Health Insurance", "ESOPs", "Ola Cab Credits", "Flexible Hours"] },
    source: "Local",
    externalId: "local-ola-android-001",
  },
  {
    title: "Product Analyst",
    company: "Groww",
    team: "Investments Product",
    location: "Bangalore, India",
    workType: "Hybrid",
    experience: "1-3 Years",
    salary: "₹10-16 LPA",
    jobType: "Full Time",
    description: "Drive data-informed product decisions for Groww's mutual fund and stock trading platform serving 10M+ investors. You'll work closely with product, design, and engineering.",
    skills: ["SQL", "Python", "Excel", "Tableau", "Product Analytics", "A/B Testing", "Data Analysis"],
    requirements: ["Strong SQL and data querying skills", "Experience with product analytics tools", "A/B testing methodology", "Clear communication of insights to stakeholders"],
    companyHighlights: { rating: 4.4, size: "1,500+ employees", industry: "Fintech / Investments", culture: "Ownership-driven, transparent", benefits: ["ESOPs", "Health Insurance", "Flexible Work", "Learning Grants"] },
    source: "Local",
    externalId: "local-groww-analyst-001",
  },
  {
    title: "SRE / Platform Engineer",
    company: "Paytm",
    team: "Site Reliability",
    location: "Noida, India",
    workType: "Hybrid",
    experience: "3-6 Years",
    salary: "₹15-28 LPA",
    jobType: "Full Time",
    description: "Ensure 99.99% uptime for Paytm's payment systems handling ₹1B+ daily transactions. Own observability, incident response, and reliability improvements.",
    skills: ["Linux", "Python", "Kubernetes", "Prometheus", "Grafana", "AWS", "CI/CD", "Go"],
    requirements: ["Strong Linux and scripting skills", "Kubernetes administration", "Monitoring with Prometheus/Grafana", "On-call incident management experience"],
    companyHighlights: { rating: 3.7, size: "7,000+ employees", industry: "Fintech", culture: "High scale, high pressure", benefits: ["Health Insurance", "Paytm Benefits", "ESOPs", "Shift Allowance"] },
    source: "Local",
    externalId: "local-paytm-sre-001",
  },
  {
    title: "UI/UX Designer",
    company: "Freshworks",
    team: "Product Design",
    location: "Chennai, India",
    workType: "Hybrid",
    experience: "2-5 Years",
    salary: "₹12-22 LPA",
    jobType: "Full Time",
    description: "Design intuitive SaaS product experiences for Freshworks' CRM, helpdesk, and ITSM products used by 60,000+ businesses worldwide.",
    skills: ["Figma", "UI/UX", "Prototyping", "Design Systems", "User Research", "Accessibility", "HTML", "CSS"],
    requirements: ["Strong Figma proficiency", "Portfolio of shipped SaaS product work", "Experience building design systems", "User research and usability testing"],
    companyHighlights: { rating: 4.2, size: "5,000+ employees", industry: "SaaS / CRM", culture: "Customer-first, collaborative", benefits: ["Competitive Pay", "ESOPs", "Health Coverage", "Global Exposure"] },
    source: "Local",
    externalId: "local-freshworks-design-001",
  },
  {
    title: "Data Scientist",
    company: "MakeMyTrip",
    team: "Data Science",
    location: "Gurugram, India",
    workType: "Hybrid",
    experience: "2-5 Years",
    salary: "₹14-24 LPA",
    jobType: "Full Time",
    description: "Apply ML and statistical models to improve search rankings, price recommendations, and personalization for India's leading travel platform.",
    skills: ["Python", "Scikit-learn", "SQL", "TensorFlow", "Statistics", "A/B Testing", "Pandas", "Spark"],
    requirements: ["Strong Python and ML fundamentals", "Hands-on SQL and data analysis", "Experience with recommendation or ranking systems", "Statistical modelling expertise"],
    companyHighlights: { rating: 4.0, size: "3,000+ employees", industry: "Travel Tech", culture: "Data-first, experiment culture", benefits: ["Health Insurance", "Travel Perks", "ESOPs", "Flexible Hours"] },
    source: "Local",
    externalId: "local-mmt-ds-001",
  },
  {
    title: "Backend Developer",
    company: "BrowserStack",
    team: "Core Platform",
    location: "Mumbai, India",
    workType: "Remote",
    experience: "2-5 Years",
    salary: "₹18-30 LPA",
    jobType: "Full Time",
    description: "Build reliable, scalable backend services for BrowserStack's real-device cloud testing platform used by 50,000+ developers and QA teams globally.",
    skills: ["Ruby on Rails", "Node.js", "Python", "PostgreSQL", "Redis", "AWS", "Docker", "REST APIs"],
    requirements: ["Backend experience in Ruby on Rails or Node.js", "PostgreSQL and Redis", "Designing scalable REST APIs", "AWS cloud experience"],
    companyHighlights: { rating: 4.6, size: "1,200+ employees", industry: "Developer Tools", culture: "Remote-first, developer-loved", benefits: ["Top Salary", "Remote Work", "ESOPs", "Health Coverage"] },
    source: "Local",
    externalId: "local-browserstack-be-001",
  },
  {
    title: "iOS Developer",
    company: "Nykaa",
    team: "Mobile Engineering",
    location: "Mumbai, India",
    workType: "Hybrid",
    experience: "2-4 Years",
    salary: "₹12-20 LPA",
    jobType: "Full Time",
    description: "Build and optimize Nykaa's iOS shopping app for 25M+ monthly active users across beauty, fashion, and wellness categories.",
    skills: ["Swift", "iOS", "UIKit", "SwiftUI", "Xcode", "REST APIs", "Core Data", "MVVM"],
    requirements: ["Strong Swift and iOS development", "Published apps on the App Store", "Experience with SwiftUI", "Performance optimization for smooth animations"],
    companyHighlights: { rating: 4.0, size: "2,500+ employees", industry: "Beauty & Fashion", culture: "Creative, product-driven", benefits: ["Health Insurance", "ESOPs", "Product Discounts", "Flexible Work"] },
    source: "Local",
    externalId: "local-nykaa-ios-001",
  },
  {
    title: "Software Engineer — Remote",
    company: "Postman",
    team: "API Platform",
    location: "Remote, India",
    workType: "Remote",
    experience: "2-5 Years",
    salary: "₹20-38 LPA",
    jobType: "Full Time",
    description: "Build features for Postman's API development platform used by 25M+ developers. Work remotely from anywhere in India with a globally distributed team.",
    skills: ["JavaScript", "Node.js", "React", "TypeScript", "REST APIs", "GraphQL", "MongoDB", "AWS"],
    requirements: ["Strong JavaScript/TypeScript skills", "Experience with Node.js backends", "React frontend development", "REST and GraphQL API design"],
    companyHighlights: { rating: 4.7, size: "800+ employees", industry: "Developer Tools", culture: "Async-first, globally distributed", benefits: ["Remote Work", "Top-tier Salary", "Equity", "Home Office Stipend"] },
    source: "Local",
    externalId: "local-postman-swe-001",
  },
  {
    title: "Cybersecurity Engineer",
    company: "Zepto",
    team: "Security",
    location: "Mumbai, India",
    workType: "Hybrid",
    experience: "2-5 Years",
    salary: "₹14-24 LPA",
    jobType: "Full Time",
    description: "Protect Zepto's quick-commerce platform and customer data from threats. Own vulnerability assessments, penetration testing, and security architecture.",
    skills: ["Cybersecurity", "Python", "Linux", "SIEM", "Penetration Testing", "AWS Security", "OWASP", "Network Security"],
    requirements: ["Security certifications (CEH, OSCP preferred)", "Penetration testing experience", "AWS security best practices", "Incident response and threat hunting"],
    companyHighlights: { rating: 4.2, size: "1,000+ employees", industry: "Quick Commerce", culture: "Zero to one, high growth", benefits: ["Competitive Salary", "ESOPs", "Health Coverage", "Flexible Hours"] },
    source: "Local",
    externalId: "local-zepto-security-001",
  },
  {
    title: "QA Engineer",
    company: "Juspay",
    team: "Payments QA",
    location: "Bangalore, India",
    workType: "Hybrid",
    experience: "1-4 Years",
    salary: "₹8-15 LPA",
    jobType: "Full Time",
    description: "Ensure the reliability of Juspay's payment orchestration platform that processes billions of transactions. Build test frameworks for API, mobile, and web.",
    skills: ["Selenium", "Cypress", "Python", "JavaScript", "REST API Testing", "Postman", "SQL", "CI/CD"],
    requirements: ["Experience with Selenium or Cypress", "API testing with Postman", "Python or JavaScript scripting", "Integration with CI/CD pipelines"],
    companyHighlights: { rating: 4.3, size: "700+ employees", industry: "Fintech / Payments", culture: "Engineering excellence", benefits: ["Health Insurance", "ESOPs", "Hybrid Work", "Tech Talks"] },
    source: "Local",
    externalId: "local-juspay-qa-001",
  },
  {
    title: "Product Manager",
    company: "Dunzo",
    team: "Consumer Growth",
    location: "Bangalore, India",
    workType: "Hybrid",
    experience: "3-6 Years",
    salary: "₹18-30 LPA",
    jobType: "Full Time",
    description: "Own the consumer growth product for Dunzo's hyperlocal delivery platform. Drive retention, activation, and engagement across 8 major Indian cities.",
    skills: ["Product Management", "SQL", "Data Analysis", "A/B Testing", "User Research", "Roadmapping", "Agile"],
    requirements: ["3+ years of product management in consumer apps", "Strong data and SQL skills", "Proven track record of growth metrics improvement", "Experience in quick-commerce or food-tech preferred"],
    companyHighlights: { rating: 3.8, size: "1,000+ employees", industry: "Quick Commerce", culture: "Scrappy, mission-driven", benefits: ["ESOPs", "Health Insurance", "Dunzo Credits", "Flexible Work"] },
    source: "Local",
    externalId: "local-dunzo-pm-001",
  },
];

const seedJobs = async () => {
  try {
    const existingCount = await Job.countDocuments({ source: "Local" });
    if (existingCount >= LOCAL_JOBS.length) return;

    for (const jobData of LOCAL_JOBS) {
      const exists = await Job.findOne({ externalId: jobData.externalId });
      if (!exists) await Job.create(jobData);
    }

    const count = await Job.countDocuments({ source: "Local" });
    console.log(`✅ Job seeder: ${count} local jobs available in DB.`);
  } catch (err) {
    console.warn("⚠️  Job seeder failed:", err.message);
  }
};

export default seedJobs;
